name: cicd

on:
  push:
    branches:
    - master
  pull_request:


env:
  PLUGIN_NAME: obsidian-copilot-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Build
      id: build
      run: |
        npm install
        npm run build

    - uses: pre-commit/action@v2.0.3

    - name: Test
      id: test
      run: |
        npm run tests

    - name: Check changelog
      run: |
        VERSION=$(jq -r '.version' package.json)  
        CHANGELOG=$(sed -n -e "/## $VERSION/,/## /p" CHANGELOG.md | sed "/## /d")  
        if [ -z "$CHANGELOG" ]; then  
          echo "Error: No release notes found for this version ($VERSION) in CHANGELOG.md"  
          exit 1  
        fi  


