name: cicd

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


env:
  PLUGIN_NAME: obsidian-copilot-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Build
      id: build
      run: |
        npm install
        npm run build

    - uses: pre-commit/action@v2.0.3
